$ANSIBLE_VAULT;1.1;AES256
38333439613261636333313336383566383836306135623366646239396639356263346163653332
3439383364323163643432313238616237623864626532300a323831656432313863616264306334
31363265346137396364643736633637326563636466666662323566626638363162613134313964
3361373762373964380a386439323464613237653536373862353461376462333234666463336134
35383738373566353039383165326234393764326466633230363231373465666139316264613438
32336230383064346530333761623438336466353733376231333465633335353662363666613864
39633566363032376437316264303230353133623065663237396563373435656139623330666231
35663666396131616561336534376336653731356137633165633539643061376464363432656463
64363865353463306262616665333939373833333038653036303837383335616433363731336634
37346339373763636435306235663466646438316237353636316363636131343861633365626331
31363231653136616536623235653035613833343230623664643564393235373165393830383538
38303835656634336162393863363437626236356461656365643833393666316362383461376536
34613835383336343236666131303531663035613632303439323261336461353134663537323061
3562643136386632656663336537346230303863613731326433
